### ISSUE TITLE
Instances for HashMap

### ISSUE THREAD

**Issue by drewolson** [purescript-contrib/purescript-profunctor-lenses#107]
I noticed that many of the optics in this package have instances for [Map](https://pursuit.purescript.org/packages/purescript-ordered-collections/1.6.1/docs/Data.Map#t:Map) but not for [HashMap](https://pursuit.purescript.org/packages/purescript-unordered-collections/1.8.0/docs/Data.HashMap#t:HashMap). I would find it useful to have access to `Ix` and `At` (among others) for `HashMap`s. Would you be willing to accept a PR for this?

**Comment by garyb** [comment]
I'd prefer if we added the instances there instead perhaps, since this library is in contrib, and we tend not to add dependencies on things outside of core/contrib. That ensures we can keep the libraries up to date - when we have external dependencies, it's possible that dependencies go stale, or the owner is too busy to review/merge updates when we're trying to update things here, etc.

**Comment by drewolson** [comment]
Makes sense, thanks.
